### PR TITLE
changes from 1:1 with Sarah

### PR DESCRIPTION
**Pull request by ghost**
I changed around the order of your CSS so it read semantic selectors,
then classes, then media queries.

For mobile, we divided the nav links and the Charlie into two sections
to provide more structure. Most of the changes were based on styling
the mobile nav.

If you accept this pull request, the code in your repository will update to match mine.

### CODE REVIEW

**Comment by mdeverges** [comment]
Hey Sarah,

I thought I did this right as my live site looks right but my local files are all jacked up now. Not sure what I did. I just tried to copy the code in the live site into my local files and it's still not working. What do you suggest? Is there a way to not commit the changes I somehow made today in the github app - permanently. I keep doing this, I was testing another media query for 390 max width and now everything is a mess. I appreciate your suggestions :) Thanks!

**Comment by mdeverges** [comment]
Just checked the html and it never updated to your code, I'm missed a nav class we added. So I think I accepted it wrong.

**Comment by ghost** [comment]
Hey Mary, it looks like you merged the pull request so it should've worked. I'm not sure exactly where you're having the trouble– are you not able to commit and sync local changes?

**Comment by mdeverges** [comment]
The changes didn't go through locally. Perhaps I thought I had synced and
didn't. I was able to just copy and paste from the code on the live site
and we are in business!

I test out what you showed me with navs and set background colors so I
could see how things were working. I'd like to add one more media query as
my phone shows the About Us on 2 lines...Feeling better about this!

Thanks for all your help!

On Fri, Oct 30, 2015 at 8:18 AM, sarah hallacher notifications@github.com
wrote:

> Hey Mary, it looks like you merged the pull request so it should've
> worked. I'm not sure exactly where you're having the trouble– are you not
> able to commit and sync local changes?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mdeverges/mdeverges.github.io/pull/3#issuecomment-152553566
> .

## 

_Mary de Verges_
_480 760 3885_

**Comment by ghost** [comment]
Great!! Glad you got it sorted.

**Pull request merged**
